name = "spinogambinocasino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinocasino.com.es"
HMAC_KEY = "3b6291ffe8a10311a3d471eb68ad340c23000bdefbcada12a83130feed344364"
COOKIE_NAME = "d8z"
PLAY_PATH = "try-now"
BUTTON_ID = "pf70f0f57b7834b0992cc3441946b6b7a"
GATE_SALT = "8b21777284910625"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "dzkc"
CTA_SELECTOR = ".play-button"
